import type { Metadata } from 'next'
import { Afacad } from '@next/font/google'
import './globals.css'
import GlobalLayout from '@/components/layouts/global.layout'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const roboto = Afacad({
	weight: ['400', '500', '700'], // или другие нужные веса
	subsets: ['latin'],
	display: 'swap', // для лучшей производительности
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${roboto.className} antialiased`}>
				<GlobalLayout>{children}</GlobalLayout>
			</body>
		</html>
	)
}
